service: aqts-capture-ecosystem-switch

provider:
  name: aws
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'TEST'}
  runtime: python3.8
  memorySize: 128
  timeout: 45
  logRetentionInDays: 90
  deploymentBucket:
    name: iow-cloud-applications
  stackTags:
    "wma:applicationId": "Aquarius TS Capture Ecosystem Switch"
    "wma:contact": "Kenneth Kehl kkehl@contractor.usgs.gov"
    "wma:environment": ${self:provider.stage}
    "wma:taggingVersion": 0.0.1
    "wma:costCenter": TBD
    commitIdentifier: ${git:sha1}

custom:
  exportGitVariables: false
  accountNumber: ${ssm:/iow/aws/accountNumber}
  vpc:
    securityGroupIds: ${ssm:/iow/retriever-capture/${self:provider.stage}/securityGroupIds~split}
    subnetIds: ${ssm:/iow/aws/vpc/${self:provider.stage}/subnetIds~split}

functions:
  StartTestDb:
    handler: src.handler.start_test_db
    role: arn:aws:iam::${self:custom.accountNumber}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      MAX_RETRIES: 6
    events:
      - schedule:
          rate: cron(45 23 ? * MON-FRI *)
          enabled: true
    vpc: ${self:custom.vpc}

  StopTestDb:
    handler: src.handler.stop_test_db
    role: arn:aws:iam::${self:custom.accountNumber}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      MAX_RETRIES: 6
    events:
      - schedule:
          rate: cron(30 23 ? * MON-FRI *)
          enabled: true
    vpc: ${self:custom.vpc}

  StartQaDb:
    handler: src.handler.start_qa_db
    role: arn:aws:iam::${self:custom.accountNumber}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      MAX_RETRIES: 6
    vpc: ${self:custom.vpc}

  StopQaDb:
    handler: src.handler.stop_qa_db
    role: arn:aws:iam::${self:custom.accountNumber}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      MAX_RETRIES: 6
    events:
      - schedule:
          rate: cron(0 23 ? * FRI *)
          enabled: true
    vpc: ${self:custom.vpc}


plugins:
  - serverless-plugin-git-variables
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - Dockerfile
    - .dockerignore
    - Jenkinsfile
    - package.json
    - package-lock.json
